### ISSUE TITLE
ELMo Transformer model

### ISSUE THREAD

**Issue by stefan-it** [nelson-liu/contextual-repr-analysis#2]
Hi @nelson-liu,

thanks for sharing the code for the nice paper :)

I would really like to know, if you could share your trained ELMo Transformer model (´model.tar.gz/`) - I would like to integrate it into the [flair](https://github.com/zalandoresearch/flair) library to do more experiments with it :)

Thanks in advance,

Stefan

**Comment by nelson-liu** [comment]
Hi Stefan!
I don't think I can share that specific `model.tar.gz`, since it uses some AI2-internal code :( However, you can easily train your own with the instructions at https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md 

It's possible that there's already a pretrained model for this---I'd raise an issue on the allennlp repo about it.

Hope that helps!

**Comment by nelson-liu** [comment]
Ah, I see that you are already aware of this ( https://github.com/zalandoresearch/flair/pull/399 ). I'd be surprised if the one you trained yourself yields results that are significantly different from the model I used in the paper; they're both just the Peters et al. "Dissecting Contextual Representations" model, after all.

I'm closing this for now, but feel free to follow up with more questions if you have any---happy to answer.

**Comment by stefan-it** [comment]
Thanks for the reply @nelson-liu :)

I really like ELMo transformer implementation in ` allennlp`, as it is very easy to use, I trained a few models for other languages and it is very fast. (In contrast to the original ELMo TensorFlow code...)

So training a model from scratch will be on my todo list :)
